### ISSUE TITLE
Templates compiled with Lodash aren't AMD compatible

### ISSUE THREAD

**Issue by eitanmk** [gruntjs/grunt-contrib-jst#18]
Not sure if this is really an issue for Lodash. With the switch of this module to use Lodash instead of underscore, I thought it should at least get mentioned here.

It seems that the way Lodash compiles templates is different from how underscore.js compiled them. Executing compiled Lodash templates in the browser relies on the presence of a global _ being defined, which AMD discourages.

Lodash compiled templates get the following in the template boilerplate after compilation:

``` javascript
__e = _.escape,
```

I don't think underscore.js introduced such a dependency...

(In my setup, I'm actually wrapping frameworks for AMD and using noConflict to not leak any globals. So I won't have a global _ for this to use at runtime.)

Perhaps there should be a way to let the amdWrapper code know what AMD module name to insert as an AMD dependency (and use 'underscore' as a default)? So the line that gets inserted for the AMD would read like:

``` javascript
define(['<underscore/module/path>'], function(_) {
```

**Comment by eTorAken** [comment]
This library do the trick: https://github.com/terryweiss/grunt-template-module
